#! /bin/bash
gnome-terminal -e 'python bootstrap.py'
sleep 2
gnome-terminal -e 'python rest.py -p 5001'
sleep 2
gnome-terminal -e 'python rest.py -p 5002'
sleep 2
gnome-terminal -e 'python rest.py -p 5003'
sleep 2
gnome-terminal -e 'python rest.py -p 5004'